#!/usr/bin/env fish

# test_bf ::
#   FilePath -> -- ^ Haskell code to be compiled and run
#   String -> -- ^ Expected output
#   IO ()
function test_bf
    set hs_path $argv[1]
    set bf_path examples/(basename $argv[1] .hs).bf
    set expected $argv[2]

    echo "=== $hs_path ==="

    rm -f $bf_path
    set hs2bf_bin (cabal list-bin hs2bf-exe)
    echo $hs2bf_bin
    $hs2bf_bin --make $hs_path > $bf_path

#    set result (time -f 'user:%U sys:%S' bfi/bfi $bf_path)
    set result (time bfi/bfi $bf_path)
    
    if test "$result" = "$expected"
        set_color green
        echo "PASSED"
        set_color normal
    else
        set_color red
        echo "FAILED"
        set_color normal
        echo "expected: " $expected
        echo "actual: " $result
    end
    
    echo ""
end


test_bf examples/Halt.hs ""
and test_bf examples/Const.hs "~"
and test_bf examples/ExplicitCase.hs "o"
and test_bf examples/Hello.hs "Hello!"
and test_bf examples/LocalFun.hs "~"
and test_bf examples/Lambda.hs "A"
and test_bf examples/Arithmetic.hs "o"
and test_bf examples/ShowList.hs "123"
and test_bf examples/QuickSort.hs "best"
# and test_bf examples/TypeClass.hs
# and test_bf examples/ConstPattern.hs
# and test_bf examples/
