name:                hs2bf
version:             0.1.0.0
github:              "helvm/hs2bf"
author:              "Kamil Adam"
maintainer:          "kamil.adam.zabinski@gmail.com"

extra-source-files:
- docs/README.md
- docs/CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/helvm/hs2bf#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- array
- parsec
- pretty-simple

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: hs/src
  dependencies:
    - base >=4.14 && <5
    - containers
    - mtl
    - array
    - filepath
    - directory
    - haskell-src

executables:
  hs2bf-exe:
    main:                Main.hs
    source-dirs:         hs/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs2bf
    - filepath

tests:
  hs2bf-test:
    main:                Spec.hs
    source-dirs:         hs/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    build-tools:
      - tasty-discover:tasty-discover
